php:
  preset: laravel
  version: 8
  tab-width: 2
  use-tabs: true
  finder:
    exclude:
      - 'public'
      - 'storage'
      - 'vendor'
    name: '*.php'
    not-name:
      - '*.blade.php'
js:
  tab-width: 2
  use-tabs: true
  semicolons: false
  finder:
    exclude:
      - 'public'
      - 'node_modules'
css:
  tab-width: 2
  use-tabs: true

vue:
  tab-width: 2
  use-tabs: true
  semicolons: false
