php:
  preset: laravel
  version: 8
  tab-width: 2
  use-tabs: true
  finder:
    not-name:
      - index.php
      - server.php
js:
  tab-width: 2
  use-table: true
  finder:
    not-name:
      - webpack.mix.js
css:
  tab-width: 2
  use-tabs: true

vue:
  tab-width: 2
  use-tabs: true
