name: Forge Deployment

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  release:
    name: Release Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 'lts/*'

      - name: Install Dependencies
        run: npm install

      - name: Run Semantic Release
        env:
          GH_TOKEN: ${{ secrets.SM_RELEASE}}
          GITHUB_TOKEN: ${{ secrets.VERAN }}
        run: npx semantic-release

  create:
    name: Create New Branch
    needs: [release]
    runs-on: ubuntu-latest

    steps:
      - name: Create Latest Branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.VERAN }}
        with:
          branch: latest
          sha: ${{ github.sha }}

  compile:
    name: Craft Jetstream App
    needs: [create, release]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Latest
        uses: actions/checkout@v3
        with:
          ref: latest

      - name: Generate .env File
        run: echo "${{ secrets.MAIN_ENV }}" > .env

      - run: sudo chown -R $(id -u):$(id -g) .env
      - run: chmod -R 777 storage bootstrap/cache

      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: '8.1'

      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Install Node
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 'lts/*'

      - run: npm install
      - run: npm run prod --force

      - name: Commit Assets to Latest
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actor
          message: 'chore(deploy): deploy main code to production'
          add: '-f public/'
          push: '-f origin latest'

  deploy:
    name: Deploy to Laravel Forge
    needs: [compile, create, release]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Production Code
        uses: jbrooksuk/laravel-forge-action@v1.0.2
        with:
          api_key: ${{ secrets.FID }}
          server_id: ${{ secrets.SID }}
          site_id: ${{ secrets.WID }}

  remove:
    name: Remove Latest Branch
    needs: [deploy, compile, create, release]
    runs-on: ubuntu-latest

    steps:
      - name: Delete Latest
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.VERAN }}
          branches: latest
