name: Forge Deployment

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  create:
    name: Create New Branch
    runs-on: ubuntu-latest

    steps:
      - name: create latest branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.VERAN }}
        with:
          branch: latest
          sha: ${{ github.sha }}

  compile:
    name: Craft Jetstream App
    needs: [create]
    runs-on: ubuntu-latest

    steps:
      - name: checkout latest
        uses: actions/checkout@v3
        with:
          ref: latest

      - name: generate .env file
        run: echo "${{ secrets.MAIN_ENV }}" > .env

      - run: sudo chown -R $(id -u):$(id -g) .env
      - run: chmod -R 777 storage bootstrap/cache

      - name: install php
        uses: shivammathur/setup-php@master
        with:
          php-version: '8.1'

      - name: install composer dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: install node and npm
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 'lts/*'

      - run: npm install
      - run: npm run prod --force

      - name: commit assets to branch
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actor
          message: 'chore(deploy): deploy main code to production'
          add: '-f public/'
          push: '-f origin latest'

  deploy:
    name: Deploy to Laravel Forge
    needs: [compile, create]
    runs-on: ubuntu-latest

    steps:
      - name: deploy production code
        uses: jbrooksuk/laravel-forge-action@v1.0.2
        with:
          api_key: ${{ secrets.FID }}
          server_id: ${{ secrets.SID }}
          site_id: ${{ secrets.WID }}

  remove:
    name: Remove Latest Branch
    needs: [deploy, compile, create]
    runs-on: ubuntu-latest

    steps:
      - name: delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.VERAN }}
          branches: latest
