name: Semantic Release Deployment

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  release:
    name: Release Main
    runs-on: ubuntu-latest
    steps:
      - name: checkout main
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: install dependencies
        run: npm ci

      - name: run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release

  create:
    name: Create New Branch
    needs: [release]
    runs-on: ubuntu-latest

    steps:
      - name: checkout main
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: create deploying branch
        uses: peterjgrainger/action-create-branch@v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          branch: deploying
          sha: ${{ github.sha }}

  compile:
    name: Craft Jetstream App
    needs: [create, release]
    runs-on: ubuntu-latest

    steps:
      - name: checkout main
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: generate .env file
        run: echo "${{ secrets.MAIN_ENV }}" > .env

      - run: sudo chown -R $(id -u):$(id -g) .env
      - run: chmod -R 777 storage bootstrap/cache

      - name: install php
        uses: shivammathur/setup-php@master
        with:
          php-version: '8.1'

      - name: install composer dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: install node and npm
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - run: npm ci
      - run: php artisan ziggy:generate
      - run: php artisan zora:generate
      - run: npm run prod --force

      - name: commit assets to branch
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actor
          branch: deploying
          message: 'chore(deploy): deploy main code to production'
          add: '-f public/'
          pull: 'NO-PULL'
          push: '-f origin deploying'

  deploy:
    name: Deploy to Laravel Forge
    needs: [compile, create, release]
    runs-on: ubuntu-latest

    steps:
      - name: deploy production code
        uses: jbrooksuk/laravel-forge-action@v1.0.2
        with:
          api_key: ${{ secrets.FID }}
          server_id: ${{ secrets.SID }}
          site_id: ${{ secrets.WID }}
