name: Deploy Tags to Production
on:
  push:
    tags:
      - v*

  workflow_dispatch:

jobs:
  create:
    name: Create Branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create Stage-Release Branch
        uses: peterjgrainger/action-create-branch@v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          branch: release
          sha: ${{ github.sha }}

  compile:
    name: Craft Jetstream App
    needs: [create]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}
          token: ${{ secrets.GH_TOKEN }}

      - name: Generate .env file
        run: echo "${{ secrets.MAIN_ENV }}" > .env

      - run: sudo chown -R $(id -u):$(id -g) .env
      - run: chmod -R 777 storage bootstrap/cache

      - name: Generate version file
        run: echo "${{ github.event.release.tag_name }}" > VERSION

      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: '8.1'

      - name: Install composer dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Install node and npm
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - run: npm ci
      - run: php artisan ziggy:generate
      - run: php artisan zora:generate
      - run: npm run prod --force

      - name: Commit assets to branch
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actor
          branch: release
          message: 'chore(deploy): deploy main code to production'
          add: '-f public/'
          pull: 'NO-PULL'
          push: '-f origin release'

  deploy:
    name: Deploy to Laravel Forge
    needs: [compile, create]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: jbrooksuk/laravel-forge-action@v1.0.2
        with:
          api_key: ${{ secrets.FID }}
          server_id: ${{ secrets.SID }}
          site_id: ${{ secrets.WID }}
